id: P008118
initial_creation_type: ocr
source_metadata:
  id: bdr:W21700
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྒྱས་འགྲེལ།
  author: ''
  volumes:
    aad8aab41f0549348dda12b72c2bfdd8:
      image_group_id: I1KG16665
      title: ''
      volume_number: 1
      total_pages: 668
ebook_metadata:
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྒྱས་འགྲེལ།
  author: ''
  sku: P008118
  cover: cover.jpg
  layers:
  - pagination
