id: P008118
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:02:52.660499
source_metadata:
  id: bdr:W21700
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྒྱས་འགྲེལ།
  author: ''
  volumes:
    4269dfb7188a44b6becd7d78e3956db7:
      image_group_id: I1KG16665
      title: Volume 1 of dbyangs can sgra mdo'i rgyas 'grel/
      volume_number: 1
      total_pages: 668
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
