id: IECCD5F6C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:25:57+00:00'
last_modified: '2022-06-09T04:37:46.426042+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21700
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྒྱས་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C446:
      image_group_id: I1KG16665
      title: Volume 1 of dbyangs can sgra mdo'i rgyas 'grel/
      total_pages: 668
      order: 1
      base_file: C446.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
